export const assetManifest = {
  generation: {
    mode: "Codex imagegen skill",
    model: "gpt-image-2 prompt workflow",
    transparentWorkflow:
      "Flat chroma-key source generated by image skill, then locally converted to PNG alpha."
  },
  videos: {
    intro: "/assets/video/piantou.mp4",
    poster: "/assets/video/piantou_poster.jpg",
    cutscene: "/assets/video/cg1.mp4",
    cutscenePoster: "/assets/video/CG_poster.jpg",
    finale: "/assets/video/final1.mp4"
  },
  ui: {
    startButton: "/assets/ui/start_button.png"
  },
  backgrounds: {
    prologue_mountain_bus_arrival: "/assets/backgrounds/prologue_mountain_bus_arrival.png",
    town_ground_base: "/assets/backgrounds/town_ground_base.png",
    interior_empty_base: "/assets/backgrounds/interior_empty_base.png",
    scene3_hanfu_exterior: "/assets/backgrounds/scene3_hanfu_exterior.png",
    scene4_hanfu_interior: "/assets/backgrounds/scene4_hanfu_interior.png",
    scene5_dressingroom: "/assets/backgrounds/scene5_dressingroom.png",
    scene6_mainstreet_horror: "/assets/backgrounds/scene6_mainstreet_horror.png"
  },
  sprites: {
    xiaoyue_modern_spritesheet: "/assets/sprites/xiaoyue_modern_spritesheet.png",
    npc_teahouse_elder_spritesheet: "/assets/sprites/npc_teahouse_elder_spritesheet.png",
    npc_inn_child_spritesheet: "/assets/sprites/npc_inn_child_spritesheet.png",
    npc_grocery_clerk_spritesheet: "/assets/sprites/npc_grocery_clerk_spritesheet.png"
  },
  worldImages: {
    building_teahouse: "/assets/buildings/building_teahouse.png",
    building_inn: "/assets/buildings/building_inn.png",
    building_grocery: "/assets/buildings/building_grocery.png",
    building_hanfu: "/assets/buildings/building_hanfu.png",
    prop_well: "/assets/props/prop_well.png",
    prop_town_sign: "/assets/props/prop_town_sign.png",
    prop_stone_tablet: "/assets/props/prop_stone_tablet.png",
    prop_bench: "/assets/props/prop_bench.png",
    prop_lantern_pair: "/assets/props/prop_lantern_pair.png",
    prop_calendar_board: "/assets/props/prop_calendar_board.png",
    prop_bridge_marker: "/assets/props/prop_bridge_marker.png",
    prop_umbrella_stand: "/assets/props/prop_umbrella_stand.png",
    furn_tea_table: "/assets/furniture/furn_tea_table.png",
    furn_teahouse_counter: "/assets/furniture/furn_teahouse_counter.png",
    furn_inn_counter: "/assets/furniture/furn_inn_counter.png",
    furn_bed: "/assets/furniture/furn_bed.png",
    furn_grocery_shelf: "/assets/furniture/furn_grocery_shelf.png",
    furn_grocery_counter: "/assets/furniture/furn_grocery_counter.png",
    furn_wall_shelf: "/assets/furniture/furn_wall_shelf.png",
    furn_altar_table: "/assets/furniture/furn_altar_table.png"
  },
  portraits: {
    xiaoyue_normal_modern: "/assets/portraits/xiaoyue_normal_modern.png",
    xiaoyue_scared_guifei: "/assets/portraits/xiaoyue_scared_guifei.png",
    xiaoyue_possessed_guifei: "/assets/portraits/xiaoyue_possessed_guifei.png",
    linya_normal_modern: "/assets/portraits/linya_normal_modern.png",
    linya_surprised_modern: "/assets/portraits/linya_surprised_modern.png",
    npc_teahouse_elder: "/assets/portraits/npc_teahouse_elder.png",
    npc_inn_child: "/assets/portraits/npc_inn_child.png",
    npc_grocery_clerk: "/assets/portraits/npc_grocery_clerk.png",
    laobanniang_normal: "/assets/portraits/laobanniang_normal.png",
    laobanniang_creepy: "/assets/portraits/laobanniang_creepy.png"
  }
} as const;

export type BackgroundKey = keyof typeof assetManifest.backgrounds;
export type SpriteKey = keyof typeof assetManifest.sprites;
export type WorldImageKey = keyof typeof assetManifest.worldImages;
export type PortraitKey = keyof typeof assetManifest.portraits;
export type UiKey = keyof typeof assetManifest.ui;
export type VideoKey = keyof typeof assetManifest.videos;
